import { NO_UPGRADES, type Scheme, type WeaponSetting } from '@wr/sim';

const w = (ammo: number, power = 3, delay = 0, crate = 2): WeaponSetting => ({
  ammo,
  power,
  delay,
  crate,
});
const INF = -1;

const BASE: Omit<Scheme, 'id' | 'name' | 'weapons'> = {
  turnTime: 45,
  retreatTime: 5,
  hotSeatTime: 5,
  roundTime: 15 * 60,
  wormHealth: 100,
  wormsPerTeam: 4,
  fallDamage: true,
  wormSelect: false,
  artillery: false,
  suddenDeath: 'health1',
  waterRise: 20,
  wind: 1,
  mines: 8,
  mineFuse: 3,
  duds: true,
  barrels: 4,
  crateChance: 40,
  healthCrateShare: 0.4,
  healthCrate: 25,
  indestructible: false,
  upgrades: NO_UPGRADES,
};

/** The default: plenty of basic weapons, limited powerful ones. */
export const INTERMEDIATE: Scheme = {
  ...BASE,
  id: 'intermediate',
  name: 'Intermediate',
  weapons: {
    bazooka: w(INF),
    grenade: w(INF),
    cluster: w(5),
    homing: w(2, 3, 2),
    mortar: w(4),
    pigeon: w(1, 3, 3),
    shotgun: w(INF),
    handgun: w(INF),
    uzi: w(2),
    minigun: w(1, 3, 2),
    longbow: w(2),
    firepunch: w(INF),
    bat: w(1),
    prod: w(INF),
    dynamite: w(1),
    mine: w(2),
    airstrike: w(1, 3, 2),
    banana: w(1, 3, 3),
    hhg: w(1, 3, 3),
    sheep: w(1),
    supersheep: w(1, 3, 2),
    girder: w(2),
    teleport: w(2),
    blowtorch: w(INF),
    drill: w(INF),
    parachute: w(2),
    rope: w(5),
    sheeplauncher: w(0, 3, 0, 1),
    molebomb: w(1, 3, 3),
    molesquad: w(0, 3, 0, 1),
    oldwoman: w(0, 3, 0, 1),
    madcows: w(0, 3, 0, 1),
    salvation: w(0, 3, 0, 1),
    donkey: w(0, 3, 0, 1),
    mbbomb: w(0, 3, 0, 1),
    axe: w(1, 3, 2),
    dragonball: w(1, 3, 2),
    kamikaze: w(1, 3, 3),
    suicide: w(1, 3, 4),
    petrol: w(2, 3, 2),
    skunk: w(1, 3, 3),
    flamethrower: w(1, 3, 3),
    napalm: w(1, 3, 3),
    mail: w(1, 3, 4),
    minestrike: w(1, 3, 3),
    carpet: w(0, 3, 0, 1),
    frenchsheep: w(0, 3, 0, 1),
    skipgo: w(INF, 3, 0, 0),
    surrender: w(INF, 3, 0, 0),
  },
};

/** Bazooka and Grenade: pure ballistics, no crates, no clutter. */
export const BNG: Scheme = {
  ...BASE,
  id: 'bng',
  name: 'BnG',
  turnTime: 30,
  roundTime: 20 * 60,
  suddenDeath: 'water',
  mines: 0,
  barrels: 0,
  crateChance: 0,
  weapons: {
    bazooka: w(INF, 3, 0, 0),
    grenade: w(INF, 3, 0, 0),
    blowtorch: w(INF, 3, 0, 0),
    drill: w(INF, 3, 0, 0),
    rope: w(INF, 3, 0, 0),
    skipgo: w(INF, 3, 0, 0),
    surrender: w(INF, 3, 0, 0),
  },
};

/** Tighter competitive play: fewer power weapons, fewer crates. */
export const PRO: Scheme = {
  ...BASE,
  id: 'pro',
  name: 'Pro',
  crateChance: 20,
  mines: 5,
  barrels: 3,
  weapons: {
    bazooka: w(INF),
    grenade: w(INF),
    cluster: w(2),
    homing: w(1, 3, 3),
    mortar: w(2),
    pigeon: w(1, 3, 4),
    shotgun: w(INF),
    handgun: w(INF),
    uzi: w(1),
    longbow: w(1, 3, 2),
    firepunch: w(INF),
    bat: w(1, 3, 1),
    prod: w(INF),
    dynamite: w(1, 3, 1),
    mine: w(1),
    airstrike: w(1, 3, 3),
    banana: w(1, 3, 4),
    hhg: w(0, 3, 0, 1),
    sheep: w(1, 3, 1),
    supersheep: w(1, 3, 3),
    girder: w(1),
    teleport: w(1),
    blowtorch: w(INF),
    drill: w(INF),
    parachute: w(1),
    rope: w(3),
    skipgo: w(INF, 3, 0, 0),
    surrender: w(INF, 3, 0, 0),
  },
};

/** Short turns and an early, fast flood: plan under pressure. */
export const ELITE: Scheme = {
  ...BASE,
  id: 'elite',
  name: 'Elite',
  turnTime: 30,
  retreatTime: 3,
  roundTime: 7 * 60,
  suddenDeath: 'water',
  waterRise: 45,
  crateChance: 30,
  weapons: {
    bazooka: w(INF),
    grenade: w(INF),
    cluster: w(3),
    mortar: w(3),
    homing: w(1, 3, 3),
    shotgun: w(3),
    uzi: w(1),
    firepunch: w(INF),
    bat: w(1),
    prod: w(INF),
    dynamite: w(1),
    mine: w(2),
    airstrike: w(1, 3, 3),
    banana: w(1, 3, 3),
    hhg: w(1, 3, 4),
    sheep: w(1),
    supersheep: w(1),
    girder: w(1),
    teleport: w(1),
    blowtorch: w(INF),
    drill: w(INF),
    parachute: w(1),
    rope: w(2),
    skipgo: w(INF, 3, 0, 0),
    surrender: w(INF, 3, 0, 0),
  },
};

/** Ten seconds to think, one second to act. Pure chaos. */
export const HYSTERIA: Scheme = {
  ...BASE,
  id: 'hysteria',
  name: 'Hysteria',
  hotSeatTime: 10,
  turnTime: 1,
  retreatTime: 3,
  crateChance: 30,
  weapons: {
    bazooka: w(INF),
    grenade: w(INF),
    mortar: w(INF),
    uzi: w(INF),
    shotgun: w(INF),
    firepunch: w(INF),
    dynamite: w(INF),
    airstrike: w(INF),
    bat: w(INF),
    teleport: w(INF),
    hhg: w(1),
    skipgo: w(INF, 3, 0, 0),
    surrender: w(INF, 3, 0, 0),
  },
};

/** Indestructible caves, only a rope to start with: race for the crates. */
export const SHOPPER: Scheme = {
  ...BASE,
  id: 'shopper',
  name: 'Shopper',
  turnTime: 30,
  retreatTime: 3,
  roundTime: 20 * 60,
  suddenDeath: 'water',
  mines: 0,
  barrels: 0,
  crateChance: 100,
  healthCrateShare: 0.15,
  indestructible: true,
  weapons: {
    rope: w(INF, 3, 0, 0),
    parachute: w(INF, 3, 0, 0),
    bazooka: w(0, 3, 0, 4),
    grenade: w(0, 3, 0, 4),
    cluster: w(0, 3, 0, 2),
    homing: w(0, 3, 0, 2),
    mortar: w(0, 3, 0, 2),
    pigeon: w(0, 3, 0, 1),
    uzi: w(0, 3, 0, 2),
    handgun: w(0, 3, 0, 3),
    longbow: w(0, 3, 0, 2),
    shotgun: w(0, 3, 0, 3),
    firepunch: w(0, 3, 0, 3),
    bat: w(0, 3, 0, 3),
    prod: w(0, 3, 0, 3),
    dynamite: w(0, 3, 0, 3),
    mine: w(0, 3, 0, 2),
    banana: w(0, 3, 0, 1),
    hhg: w(0, 3, 0, 1),
    sheep: w(0, 3, 0, 2),
    supersheep: w(0, 3, 0, 1),
    skipgo: w(INF, 3, 0, 0),
    surrender: w(INF, 3, 0, 0),
  },
};

/** Sudden Death from the first turn: everyone poisoned, the water rising. */
export const ARMAGEDDON: Scheme = {
  ...INTERMEDIATE,
  id: 'armageddon',
  name: 'Armageddon',
  turnTime: 30,
  roundTime: 0,
  wormHealth: 150,
  suddenDeath: 'nuclear',
  waterRise: 20,
};

export const SCHEMES: Scheme[] = [INTERMEDIATE, PRO, ELITE, BNG, HYSTERIA, SHOPPER, ARMAGEDDON];

/** Menu blurbs, and the map style that suits each scheme. */
export const SCHEME_INFO: Record<string, { description: string; style?: 'island' | 'cavern' }> = {
  intermediate: { description: 'Классика: базовое оружие без ограничений, мощное — по чуть-чуть.' },
  pro: { description: 'Соревновательный вариант: меньше хаоса, меньше ящиков, больше точности.' },
  elite: { description: 'Ходы по 30 секунд, через 7 минут быстро поднимается вода.' },
  bng: { description: 'Только базука и граната. Читай ветер, считай отскоки.' },
  hysteria: { description: '10 секунд подумать, 1 секунда на ход. Безумие.' },
  shopper: {
    description: 'Неразрушаемые пещеры, только верёвка. Собирай ящики и атакуй.',
    style: 'cavern',
  },
  armageddon: { description: 'Внезапная смерть сразу: 150 HP, яд и поднимающаяся вода.' },
};

export function schemeById(id: string): Scheme {
  return SCHEMES.find((s) => s.id === id) ?? INTERMEDIATE;
}
