export const TICKS_PER_SECOND = 50;
export const TICK_MS = 1000 / TICKS_PER_SECOND;

export * from './core/math';
export * from './core/rng';
export * from './core/hash';
export * from './terrain/terrain';
export * from './world/entity';
export * from './world/events';
export * from './world/world';
export * from './worm/worm';
export * from './weapons/explosion';
export * from './world/body';
export * from './world/gravestone';
export * from './weapons/weapon';
export * from './game/commands';
export * from './game/scheme';
export * from './game/game';
export * from './weapons/projectile';
export * from './weapons/blast';
export * from './weapons/defs';
export * from './weapons/mine';
export * from './weapons/fire';
export * from './weapons/barrel';
export * from './weapons/sheep';
export * from './weapons/digTool';
export * from './weapons/rope';
export * from './weapons/crate';
export * from './weapons/homing';
export * from './weapons/pigeon';
export * from './weapons/gunfire';
